/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as CategoryCategorySlugSubcategorySlugRouteImport } from './routes/category.$categorySlug.$subcategorySlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugSubcategorySlugRoute =
  CategoryCategorySlugSubcategorySlugRouteImport.update({
    id: '/$subcategorySlug',
    path: '/$subcategorySlug',
    getParentRoute: () => CategoryCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/category/$categorySlug'
    | '/category/$categorySlug/$subcategorySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/category/$categorySlug'
    | '/category/$categorySlug/$subcategorySlug'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/category/$categorySlug'
    | '/category/$categorySlug/$subcategorySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug/$subcategorySlug': {
      id: '/category/$categorySlug/$subcategorySlug'
      path: '/$subcategorySlug'
      fullPath: '/category/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof CategoryCategorySlugSubcategorySlugRouteImport
      parentRoute: typeof CategoryCategorySlugRoute
    }
  }
}

interface CategoryCategorySlugRouteChildren {
  CategoryCategorySlugSubcategorySlugRoute: typeof CategoryCategorySlugSubcategorySlugRoute
}

const CategoryCategorySlugRouteChildren: CategoryCategorySlugRouteChildren = {
  CategoryCategorySlugSubcategorySlugRoute:
    CategoryCategorySlugSubcategorySlugRoute,
}

const CategoryCategorySlugRouteWithChildren =
  CategoryCategorySlugRoute._addFileChildren(CategoryCategorySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
