/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapCategoriesDotxmlRouteImport } from './routes/sitemap-categories[.]xml'
import { Route as SitemapIdeasDotxmlRouteImport } from './routes/sitemap-ideas[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CalculatorIndexRouteImport } from './routes/calculator.index'
import { Route as CalculatorSlugRouteImport } from './routes/calculator.$slug'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as IdeaSlugRouteImport } from './routes/idea.$slug'
import { Route as ListIndexRouteImport } from './routes/list.index'
import { Route as ListSlugRouteImport } from './routes/list.$slug'
import { Route as CategoryCategorySlugIndexRouteImport } from './routes/category.$categorySlug.index'
import { Route as CategoryCategorySlugSubcategorySlugRouteImport } from './routes/category.$categorySlug.$subcategorySlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCategoriesDotxmlRoute = SitemapCategoriesDotxmlRouteImport.update({
  id: '/sitemap-categories.xml',
  path: '/sitemap-categories.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIdeasDotxmlRoute = SitemapIdeasDotxmlRouteImport.update({
  id: '/sitemap-ideas.xml',
  path: '/sitemap-ideas.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIndexRoute = CalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorSlugRoute = CalculatorSlugRouteImport.update({
  id: '/calculator/$slug',
  path: '/calculator/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaSlugRoute = IdeaSlugRouteImport.update({
  id: '/idea/$slug',
  path: '/idea/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListIndexRoute = ListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSlugRoute = ListSlugRouteImport.update({
  id: '/list/$slug',
  path: '/list/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugIndexRoute =
  CategoryCategorySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategoryCategorySlugRoute,
  } as any)
const CategoryCategorySlugSubcategorySlugRoute =
  CategoryCategorySlugSubcategorySlugRouteImport.update({
    id: '/$subcategorySlug',
    path: '/$subcategorySlug',
    getParentRoute: () => CategoryCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gdpr': typeof GdprRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-ideas.xml': typeof SitemapIdeasDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculator/$slug': typeof CalculatorSlugRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/idea/$slug': typeof IdeaSlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/list/': typeof ListIndexRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/category/$categorySlug/': typeof CategoryCategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gdpr': typeof GdprRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-ideas.xml': typeof SitemapIdeasDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculator/$slug': typeof CalculatorSlugRoute
  '/idea/$slug': typeof IdeaSlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/blog': typeof BlogIndexRoute
  '/calculator': typeof CalculatorIndexRoute
  '/list': typeof ListIndexRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/category/$categorySlug': typeof CategoryCategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/gdpr': typeof GdprRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sign-in': typeof SignInRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-ideas.xml': typeof SitemapIdeasDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculator/$slug': typeof CalculatorSlugRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/idea/$slug': typeof IdeaSlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/list/': typeof ListIndexRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/category/$categorySlug/': typeof CategoryCategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/contact'
    | '/disclaimer'
    | '/gdpr'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/search'
    | '/services'
    | '/sign-in'
    | '/sitemap-categories.xml'
    | '/sitemap-ideas.xml'
    | '/sitemap-index.xml'
    | '/sitemap-pages.xml'
    | '/terms'
    | '/blog/$slug'
    | '/calculator/$slug'
    | '/category/$categorySlug'
    | '/idea/$slug'
    | '/list/$slug'
    | '/blog/'
    | '/calculator/'
    | '/list/'
    | '/category/$categorySlug/$subcategorySlug'
    | '/category/$categorySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/contact'
    | '/disclaimer'
    | '/gdpr'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/search'
    | '/services'
    | '/sign-in'
    | '/sitemap-categories.xml'
    | '/sitemap-ideas.xml'
    | '/sitemap-index.xml'
    | '/sitemap-pages.xml'
    | '/terms'
    | '/blog/$slug'
    | '/calculator/$slug'
    | '/idea/$slug'
    | '/list/$slug'
    | '/blog'
    | '/calculator'
    | '/list'
    | '/category/$categorySlug/$subcategorySlug'
    | '/category/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/contact'
    | '/disclaimer'
    | '/gdpr'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/search'
    | '/services'
    | '/sign-in'
    | '/sitemap-categories.xml'
    | '/sitemap-ideas.xml'
    | '/sitemap-index.xml'
    | '/sitemap-pages.xml'
    | '/terms'
    | '/blog/$slug'
    | '/calculator/$slug'
    | '/category/$categorySlug'
    | '/idea/$slug'
    | '/list/$slug'
    | '/blog/'
    | '/calculator/'
    | '/list/'
    | '/category/$categorySlug/$subcategorySlug'
    | '/category/$categorySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GdprRoute: typeof GdprRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SignInRoute: typeof SignInRoute
  SitemapCategoriesDotxmlRoute: typeof SitemapCategoriesDotxmlRoute
  SitemapIdeasDotxmlRoute: typeof SitemapIdeasDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CalculatorSlugRoute: typeof CalculatorSlugRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRouteWithChildren
  IdeaSlugRoute: typeof IdeaSlugRoute
  ListSlugRoute: typeof ListSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CalculatorIndexRoute: typeof CalculatorIndexRoute
  ListIndexRoute: typeof ListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-categories.xml': {
      id: '/sitemap-categories.xml'
      path: '/sitemap-categories.xml'
      fullPath: '/sitemap-categories.xml'
      preLoaderRoute: typeof SitemapCategoriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ideas.xml': {
      id: '/sitemap-ideas.xml'
      path: '/sitemap-ideas.xml'
      fullPath: '/sitemap-ideas.xml'
      preLoaderRoute: typeof SitemapIdeasDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof CalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/$slug': {
      id: '/calculator/$slug'
      path: '/calculator/$slug'
      fullPath: '/calculator/$slug'
      preLoaderRoute: typeof CalculatorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$slug': {
      id: '/idea/$slug'
      path: '/idea/$slug'
      fullPath: '/idea/$slug'
      preLoaderRoute: typeof IdeaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/': {
      id: '/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof ListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$slug': {
      id: '/list/$slug'
      path: '/list/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof ListSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug/': {
      id: '/category/$categorySlug/'
      path: '/'
      fullPath: '/category/$categorySlug/'
      preLoaderRoute: typeof CategoryCategorySlugIndexRouteImport
      parentRoute: typeof CategoryCategorySlugRoute
    }
    '/category/$categorySlug/$subcategorySlug': {
      id: '/category/$categorySlug/$subcategorySlug'
      path: '/$subcategorySlug'
      fullPath: '/category/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof CategoryCategorySlugSubcategorySlugRouteImport
      parentRoute: typeof CategoryCategorySlugRoute
    }
  }
}

interface CategoryCategorySlugRouteChildren {
  CategoryCategorySlugSubcategorySlugRoute: typeof CategoryCategorySlugSubcategorySlugRoute
  CategoryCategorySlugIndexRoute: typeof CategoryCategorySlugIndexRoute
}

const CategoryCategorySlugRouteChildren: CategoryCategorySlugRouteChildren = {
  CategoryCategorySlugSubcategorySlugRoute:
    CategoryCategorySlugSubcategorySlugRoute,
  CategoryCategorySlugIndexRoute: CategoryCategorySlugIndexRoute,
}

const CategoryCategorySlugRouteWithChildren =
  CategoryCategorySlugRoute._addFileChildren(CategoryCategorySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  GdprRoute: GdprRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SignInRoute: SignInRoute,
  SitemapCategoriesDotxmlRoute: SitemapCategoriesDotxmlRoute,
  SitemapIdeasDotxmlRoute: SitemapIdeasDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CalculatorSlugRoute: CalculatorSlugRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRouteWithChildren,
  IdeaSlugRoute: IdeaSlugRoute,
  ListSlugRoute: ListSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CalculatorIndexRoute: CalculatorIndexRoute,
  ListIndexRoute: ListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
